### ISSUE TITLE
Sensor error 

### ISSUE THREAD

**Issue by yog-admin-git** [HON95/prometheus-esp8266-dht-exporter#3]
Hi,

Testing this for couple of weeks, on both DHT22 and DHT11 and NODE MCU and Wemos D1 Mini.  Boards are working fine for few hours then start throwing "Sensor error". I have to reset manually to make them work again.
Is it due to power supply issue or something else, what’s the recommended setup for stable operation?

**Comment by HON95** [comment]
Hmm, I have no clue. Could be a power issue as you mention. I'm currently using a DHT11 powered by the 3V port of some cheap ESP8266 board.
